version: "3.7"

services:
  app:
    build: ./docker
    image: enzovarellap/php_mvc
    ports:
      - "8080:80"
    volumes:
      # Mount source-code for development
      - ./:/var/www
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysql-data: